language: node_js
node_js:
 - "stable" 
install:
  - cd Task1
  - npm install
  - cd ..
  - cd Task2
  - npm install
  - cd ..
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE postgres;" -U postgres
script: 
  - cd Task1
  - npm start & 
  - npm test
  - cd ..
  - cd Task2
  - npm start
  - npm test