language: node_js
node_js:
 - "stable" 
install:
  - cd Task1
  - npm install
  - cd ..
  - cd Task2
  - npm install
  - cd ..
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
  - psql -c "CREATE DATABASE DB;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script: 
  - cd Task1
  - npm start & 
  - npm test
  - cd ..
  - cd Task2
  - npm start
  - npm test