language: node_js
node_js:
 - "stable" 
install: 
  - cd Task1
  - npm install
  - cd ..
  - cd Task2
  - npm install
  - cd ..
  - npm install -g codecov
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script: 
  - cd Task1
  - npm test
  - cd ..
  - cd Task2
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov