language: node_js
node_js:
 - "stable" 
install:
  - cd Task1
  - npm install
  - cd ..
  - cd Task2
  - npm install
  - cd ..
before_script:
  - psql -c 'create database DB;' -U postgres:root
script:
  - cd Task1
  - npm start & 
  - npm test
  - cd ..
  - cd Task2
  - npm start
  - npm test