language: node_js
node_js:
 - "stable" 
install: 
  - cd Task1
  - npm install
  - cd ..
  - cd Task2
  - npm install
  - cd ..
  - npm install -g codecov istanbul
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script: 
  - cd Task1
  - npm run coverage
  - cd ..
  - cd Task2
  - npm run coverage