language: node_js
node_js:
 - "stable" 
install:
  - cd Task1
  - npm install
  - cd ..
  - cd Task2
  - npm install
  - cd ..
services:
  - postgresql
before_script:
  - psql -c 'create extension pgcrypto;' -U postgres
  - psql -c 'create database DB;' -U postgres
script: 
  - cd Task1
  - npm start & 
  - npm test
  - npm stop
  - cd ..
  - cd Task2
  - npm start 
  - npm test